name: CI Pipeline for Calculator App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests in Docker
        run: docker run --name contact_book_container contact-book-app python -m unittest discover -s .  # Assuming your tests are in the 'tests' folder

  dockerize:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t contact-book-app .

      - name: Run Docker Container
        run: docker run --name contact_book_container contact-book-app

      - name: Stop and Remove Container
        run: docker rm -f contact_book_container
