name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Log in to Docker Hub using the DOCKER_CREDS secret
      - name: Log in to Docker Hub
        run: |
          # Extract Docker username and password from secret
          echo ${{ secrets.DOCKER_CREDS }} | grep -oP '(?<=DOCKER_USERNAME: )\S+' > username.txt
          echo ${{ secrets.DOCKER_CREDS }} | grep -oP '(?<=DOCKER_PASSWORD: )\S+' > password.txt
          username=$(cat username.txt)
          password=$(cat password.txt)
          docker login -u $username -p $password

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t your-image-name .

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push your-image-name
