name: Simple Calculator CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run tests
      run: |
        python -m unittest discover

    # Step 5: Build Docker image (optional)
    - name: Build Docker image
      run: |
        docker build -t simple-calculator .

    # Step 6: Push Docker image to Docker Hub (optional)
    - name: Push Docker image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag simple-calculator ${{ secrets.DOCKER_USERNAME }}/simple-calculator:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/simple-calculator:latest
